[tool.poetry]
name = "nonebot-adapter-opqbot"
version = "0.1.2"
description = "OPQBot adapter for nonebot2"
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

packages = [{ include = "nonebot" }]

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.3.2"
pillow = "^10.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
