[tool.poetry]
name = "kpx"
version = "0.8.1"
description = "CLI tool for AWS configuration files and quick interogations to AWS API"
authors = ["BogdanR <367815-marius-rizac@users.noreply.gitlab.com>"]
license = "APACHE 2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.12.3"
boto3 = "^1.34.150"
prettytable = "^3.10.2"
kubernetes = "^30.1.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"
coverage = "^7.6.0"
flake8 = "^7.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
kpx = "kpx.main:app"
