[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "iotest-grader"
version = "0.0.10"
authors = [
  { name="Joe Delfino", email="jdelfino@brandeis.edu" },
]
description = "A pytest harness for input/output tests, intended for use in VSCode"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pexpect>=4.8.0",
    "pytest>=7.0",
    "pytest-clarity>=1.0.0"
]

[project.urls]
Homepage = "https://github.com/brandeis-cosi-10a/input-output-test"
Issues = "https://github.com/brandeis-cosi-10a/input-output-test/issues"
