[tool.poetry]
name = "aisetup"
version = "0.1.1"
description = "Source code repository for deeplearning.ai courses"
authors = ["Andrew Ng <ng@deeplearning.ai>"]
license = "MIT"
readme = "README.md"
package-mode=true
packages = [{ include = "aisetup", from = "src" }]
repository = "https://github.com/https-deeplearning-ai/aisetup"
keywords = ["deeplearningai", "deeplearning", "short course", "LLM"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
openai = "^1.40.6"
python-dotenv = "^1.0.1"
numpy = "^2.0.1"
folium = "^0.17.0"
ipywidgets = "^8.1.3"
ipython = "^8.26.0"
requests = "^2.32.3"
matplotlib = "^3.9.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
