[tool.poetry]
name = "s3lite"
version = "0.1.7"
description = "Minimal async s3 implementation."
authors = ["RuslanUC <dev_ruslan_uc@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
httpx = "^0.27.0"
python-dateutil = "^2.8.2"


[tool.poetry.group.dev.dependencies]
pytest-cov = "^4.1.0"
pytest = "7.4.4"
pytest-asyncio = "^0.23.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

