[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["char_counter", "cli", "tests"]

[project]
name = "char_counter_Le0Bu"
version = "0.0.1"
authors = [
  {name = "Leo Bu", email = "burimko@gmail.com"},
]

description = 'Simple program that counts the number of characters that occur only once in a string. Works through the command-line interface.'
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">= 3.12"