[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "analyser_hj3415"
version = "2.1.0"
authors = [{name = "Hyungjin Kim", email = "hj3415@gmail.com"}]
description = "Stock analyser and database processing programs"
readme = "README.md"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dependencies = [
    "utils-hj3415>=2.6.0",
    "db-hj3415>=3.3.2",
]

[project.scripts]
dbmanager = "analyser_hj3415.cli:dbmanager"
evalmanager = "analyser_hj3415.cli:evalmanager"

[project.urls]
Home = "https://www.hyungjin.kr"

[tool.flit.sdist]
exclude = [
]