[tool.poetry]
name = "mirapolis-virtualroom"
version = "0.2.8"
description = "Python API Client for Mirapolis VirtualRoom. Based on original documentation. Uses Pydantic and aiohttp."
authors = ["gulyaeve <gulyaev.e@icloud.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/gulyaeve/mirapolis_virtualroom"
repository = "https://github.com/gulyaeve/mirapolis_virtualroom"
keywords = ["mirapolis", "virtualroom"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "^3.9.3"
pydantic = "^2.6.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

