[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[project]
name = "fieldrouter"
version = "1.0.2"
description = "Data model validation for nested data routes"
authors = [
    { name = "Louis Maddox", email = "louismmx@gmail.com" },
]
dependencies = [
    "pydantic>=2.8.2",
]
requires-python = ">=3.10"
readme = "README.md"

[project.license]
text = "MIT"

[project.urls]
Homepage = "https://github.com/lmmx/fieldrouter"
Repository = "https://github.com/lmmx/fieldrouter.git"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.3.2",
]
