[tool.poetry]
name = "clouds-game"
version = "0.1.2"
description = "Mission planning simulation game to reduce cloud coverage of Earth observation satellite missions"
authors = [
    "Sven Pr√ºfer <sven.pruefer@dlr.de>"
]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
packages = [
    { include = "clouds", from = "src"}
]
include = [
    "README.md",
]

[tool.poetry.dependencies]
python = ">=3.11,<4"
immutables = ">=0.20"
pygame = ">=2.6.0"
click = ">=8.1.7"

[tool.poetry.group.dev.dependencies]
mypy = ">=1.6.0"
mypy2junit = ">=1.9.0"
lxml = ">=5.2.2"
pytest = ">=7.4.0"
pytest-cov = ">=5.0.0"
pylint = ">=3.0.2"
pylint-gitlab = ">=2.0.0"
black = { version = ">=23.10.1", extras = ["d"] }
notebook = ">= 7.0.6"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-rtd-theme = "^1.3.0"

[tool.black]
line-length = 120
target-version = ['py312']

[tool.mypy]
python_version = "3.12"

[[tool.mypy.overrides]]
module = [
    'clouds',
    'clouds.base',
    'clouds.base.model'
]
ignore_missing_imports = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = "non-ascii-name, non-ascii-module-import, too-few-public-methods, missing-module-docstring"
generated-members = "pygame.*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
