[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moconut"
version = "0.0.1"
authors = [
    { name = "Danzel Serrano", email = "danzel.serrano@gmail.com" }
]
description = "Model Construction Utils"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/dependanz/moconut"