[tool.poetry]
name = "cdrc"
version = "0.1.14"
description = ""
authors = ["marshHawk4 <kyle@jataware.com>"]
readme = "README.md"
packages = [
         {include = "cdrc"},
         {include = "cdrc/**/*.py"}
]

[tool.poetry.dependencies]
python = "^3.10"
geopandas = "^1.0.1"
pydantic = "^2.8.0"
httpx = "0.27.*"
wand = "^0.6.13"
numpy = "1.26.2"

[tool.poetry.group.dev.dependencies]
black = "^24.2.0"
flake8 = "^7.0.0"
isort = "^5.13.2"
flake8-print = "^5.0.0"
autoflake = "^2.2.1"
mypy = "^1.8.0"
ruff = "^0.3.4"

[tool.poetry.scripts]
format = "cdrc.dev.script:format"

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
line_length = 119

[tool.ruff]
line-length = 119


[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long, handled by black
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
