[tool.poetry]
name = "concave"
version = "0.1.1"
description = ""
authors = ["wph95 <2732352+wph95@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
docker = "^7.1.0"
jinja2 = "^3.1.4"
llama-index-embeddings-voyageai = "^0.1.4"
loguru = "^0.7.2"
pydantic = "^2.8.2"
fastapi = {extras = ["standard"], version = "^0.112.0"}
requests = "^2.32.3"
sqlmodel = "^0.0.21"
protobuf = "^5.27.3"
llama-index = "^0.10.65"
uvicorn = {extras = ["standard"], version = "^0.30.5"}
gunicorn = "^23.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
