[project]
name = "statute-utils"
requires-python = ">=3.11"
description = "Toolkit for Philippine rules."
version = "0.8.1"
dependencies = [
  "prelawsql >= 0.0.7",         # base
  "markdown >= 3.4.4",          # template
  "jinja2 >= 3.1.4",            # template
  "lxml >= 5.2.2",              # template
  "markdownify >= 0.13.1",      # fetch
]

[project.optional-dependencies]
dev = [
  "types-python-slugify >= 8.0.2",
  # shell
  "ipykernel >= 6.29",
  # testing
  "pytest >= 8.3",
  "pytest-cov >= 5.0",
  # docs
  "mkdocs >= 1.6.0",
  "mkdocstrings [python] >= 0.25.1",
  "mkdocs-material >= 9.5",
  # package
  "build >= 1.2.1",
  "twine >= 5.1.1",
]

[project.scripts]
builder = "statute_utils:cli"

[tool.pytest.ini_options]
minversion = "8.3"
addopts = "-ra -q --cov --doctest-modules"
testpaths = ["tests", "src/statute_utils"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
ignore = ["F401", "F403"]
fixable = ["F", "E", "W", "I001"]
select = ["F", "E", "W", "I001"]
